# NAME: Andrew Yong
# EMAIL: yong.andrew11@gmail.com
# ID: 604905807

pics = my_beaglebone.jpg connected.png copy.png build_run.png git.png 
id = 604905807
tarname = lab4a-$(id).tar.gz
tars = README Makefile

dist: $(files)
	tar -czf $(tarname) $(pics) $(tars)
