# NAME: Andrew Yong
# EMAIL: yong.andrew11@gmail.com
# ID: 604905807

files = simpsh2.c Makefile
id = 604905807

simpsh2: simpsh2.c

.PHONY: clean
clean:
	-@rm simpsh lab1-$(id).tar.gz

.PHONY: dist
dist:
	tar -czf lab1-$(id).tar.gz $(files)

.PHONY: check
check:
	./check


