#!/bin/bash

threads=(1)
iterations=(10 20 40 80 100 1000 10000 100000)
repeats=5

if [ $# -eq 0 ] || { [ "$1" != "add" ] && [ "$1" != "list" ]; }; then
	echo "which test? add or list?"
	echo "usage: $0 add/list [more options]"
	exit 1
fi
graph="plotter/lab2_$1.csv"

for i in ${threads[@]}; do
	for j in ${iterations[@]}; do
		for c in `seq 1 $repeats`; do
			./lab2_add --threads $i --iterations $j ${@:2} >> $graph || exit 1
		done
	done
done

cd plotter && ./lab2_$1.gp
